name: Run Linter

on:
  push:
    branches:
      - staging
    
jobs:
  test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts'

      - name: Install dependencies
        run: npm install

      - name: Lint JavaScript files
        run: npm run lint
  
   