name: Run Pre-Deployment Tests

on:
  push:
    branches:
     - staging

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['5.0.9']

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Setup MongoDB
      uses: mongodb-actions/setup-mongodb@v2
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Setup Redis
      uses: chenjuneking/redis-setup-action@v1
      with:
        version: 6
        hostPort: 5034
        containerPort: 6379

    - name: Start MongoDB
      uses: MongoCamp/mongodb-github-action@1.0.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    
    - name: Setup Node Js environment
      uses: actions/setup-node@v4
      with:
        node-version: "21"
      
    - name: Install dependencies
      run: npm install

      # Run the tests
    - name: Run tests
      run: npm test