name: Test MongoDB Installation

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.4.14', '5.0.9']

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Start MongoDB
      uses: MongoCamp/mongodb-github-action@1.0.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: curl http://localhost:27017